#define FUNC_LIST(x) \
x(eglGetDisplay) \
x(eglInitialize) \
x(eglChooseConfig) \
x(eglCreateWindowSurface) \
x(eglBindAPI) \
x(eglCreateContext) \
x(eglDestroyContext) \
x(eglMakeCurrent) \
x(eglSwapBuffers) \
x(eglGetProcAddress) \
x(glEnable) \
x(glDisable) \
x(glGetError) \
x(glVertexAttrib1f) \
x(glVertexAttrib2f) \
x(glVertexAttrib3f) \
x(glVertexAttrib4f) \
x(glVertexAttrib1fv) \
x(glVertexAttrib2fv) \
x(glVertexAttrib3fv) \
x(glVertexAttrib4fv) \
x(glVertexAttribPointer) \
x(glEnableVertexAttribArray) \
x(glDisableVertexAttribArray) \
x(glDrawArrays) \
x(glDrawElements) \
x(glBindBuffer) \
x(glDeleteBuffers) \
x(glGenBuffers) \
x(glBufferData) \
x(glBufferSubData) \
x(glCreateShader) \
x(glShaderSource) \
x(glCompileShader) \
x(glReleaseShaderCompiler) \
x(glDeleteShader) \
x(glShaderBinary) \
x(glCreateProgram) \
x(glAttachShader) \
x(glDetachShader) \
x(glLinkProgram) \
x(glUseProgram) \
x(glDeleteProgram) \
x(glGetActiveAttrib) \
x(glGetAttribLocation) \
x(glBindAttribLocation) \
x(glGetUniformLocation) \
x(glGetActiveUniform) \
x(glUniform1i) \
x(glUniform2i) \
x(glUniform3i) \
x(glUniform4i) \
x(glUniform1f) \
x(glUniform2f) \
x(glUniform3f) \
x(glUniform4f) \
x(glUniform1iv) \
x(glUniform2iv) \
x(glUniform3iv) \
x(glUniform4iv) \
x(glUniform1fv) \
x(glUniform2fv) \
x(glUniform3fv) \
x(glUniform4fv) \
x(glUniformMatrix2fv) \
x(glUniformMatrix3fv) \
x(glUniformMatrix4fv) \
x(glValidateProgram) \
x(glDepthRangef) \
x(glViewport) \
x(glLineWidth) \
x(glFrontFace) \
x(glCullFace) \
x(glPolygonOffset) \
x(glPixelStorei) \
x(glActiveTexture) \
x(glTexImage2D) \
x(glCopyTexImage2D) \
x(glTexSubImage2D) \
x(glCopyTexSubImage2D) \
x(glCompressedTexImage2D) \
x(glCompressedTexSubImage2D) \
x(glTexParameteri) \
x(glTexParameterf) \
x(glTexParameteriv) \
x(glTexParameterfv) \
x(glGenerateMipmap) \
x(glBindTexture) \
x(glDeleteTextures) \
x(glGenTextures) \
x(glScissor) \
x(glSampleConverage) \
x(glStencilFunc) \
x(glStencilFuncSeparate) \
x(glStencilOp) \
x(glStencilOpSeparate) \
x(glDepthFunc) \
x(glBlendEquation) \
x(glBlendEquationSeparate) \
x(glBlendFuncSeparate) \
x(glBlendFunc) \
x(glBlendColor) \
x(glColorMask) \
x(glDepthMask) \
x(glStencilMask) \
x(glStencilMaskSeparate) \
x(glClear) \
x(glClearColor) \
x(glClearDepthf) \
x(glClearStencil) \
x(glReadPixels) \
x(glBindFramebuffer) \
x(glDeleteFramebuffers) \
x(glGenFramebuffers) \
x(glBindRenderbuffer) \
x(glDeleteRenderbuffers) \
x(glGenRenderbuffers) \
x(glRenderbufferStorage) \
x(glFramebufferRenderbuffer) \
x(glFramebufferTexture2D) \
x(glCheckFramebufferStatus) \
x(glFlush) \
x(glFinish) \
x(glHint) \
x(glGetBooleanv) \
x(glGetIntegerv) \
x(glGetFloatv) \
x(glIsEnabled) \
x(glGetTexParameteriv) \
x(glGetTexParameterfv) \
x(glGetBufferParameteriv) \
x(glGetFramebufferAttachmentParameteriv) \
x(glGetRenderbufferParameteriv) \
x(glIsTexture) \
x(glGetString) \
x(glIsBuffer) \
x(glIsFramebuffer) \
x(glIsRenderbuffer) \
x(glIsShader) \
x(glGetShaderiv) \
x(glIsProgram) \
x(glGetProgramiv) \
x(glGetAttachedShaders) \
x(glGetShaderInfoLog) \
x(glGetProgramInfoLog) \
x(glGetShaderSource) \
x(glGetShaderPrecisionFormat) \
x(glGetVertexAttribfv) \
x(glGetVertexAttribiv) \
x(glGetVertexAttribPointerv) \
x(glGetUniformfv)

